defaults:
- data: zarr #to change to our own config
- dataloader: native_grid #to change to our own config
- diagnostics: evaluation
- datamodule: single
- hardware: example
# - graph: <multi_scale
# - graph: graph_AROME.yaml
- graph: existing_graph
# - graph: multi_scale
- model: graphtransformer_diffusionuncond
- training: diffusion
- _self_

# set to true to switch on config validation
config_validation: False
diagnostics:
  log:
    mlflow:
      enabled: False 
      # on_resume_create_child: False
      offline: False
      # experiment_name : 'overfit_cond_mean_sigma_10000_highnoise_steps_15k'
      # project_name: 'overfit_cond_mean_sigma_10000_highnoise_steps_15k'
      # run_name: 'overfit_cond_mean_sigma10000_highnoise_steps_15k'
      tracking_uri: 'https://mlflow.ecmwf.int'
      authentication: True
      terminal: False
    wandb:
      enabled: False
      entity: "none"
data:
    frequency: 1h 
    diagnostic: ["tp"] #variables que le modÃ¨le ne prendra pas en input mais va sortir en output : tp est la pluie, on ne la prend pas en input 
    # Ã§a peut perturber en input les variables et tout le modne fait comme Ã§a.
    forcing:
      - "z"
      # - "cos_latitude"
      # - "cos_longitude"
      # - "sin_latitude"
      # - "sin_longitude"
      # - "cos_julian_day"
      # - "cos_local_time"
      # - "sin_julian_day"
      # - "sin_local_time"
      # - "insolation"
      # - "lsm"
      # - "z"
    # normalizer:
    #   std: null
    #   max: null
    #   none: ${data.forcing}
    normalizer:
      default: "mean-std"
      max: null
      # mean-std:
      # - z
      # none: 
      # - cos_latitude
      # - cos_longitude
      # - sin_latitude
      # - sin_longitude
      # - cos_julian_day
      # - cos_local_time
      # - sin_julian_day
      # - sin_local_time
      # - lsm

dataloader:
    dataset:
        - dataset: /project/home/p200177/DE_371/datasets/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6.zarr
    grid_indices:
        _target_: anemoi.training.data.grid_indices.MaskedGrid
        nodes_name: data
        node_attribute_name: indices_connected_nodes
    training:
        start: "2020-01-01"
        end: "2020-01-03"

        select: ['10u', '10v',  '2t', 'tp','z']
    
    validation:
        start: "2023-04-01"
        end: "2023-04-03"

        select: ['10u', '10v',  '2t', 'tp','z']

    test:
        start: "2024-04-02"
        end: "2024-04-03"
        select: ['10u', '10v',  '2t', 'tp','z']

    batch_size:
      training: 1
      validation: 1
      test: 1
    num_workers:
      training: 4
      validation: 4
model:
  model:
    _target_: anemoi.models.models.AnemoiDiffusionModelEncProcDecUnconditional
  diffusion:

hardware:
  paths:
    data: /project/home/p200177/DE_371/datasets/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6
    output: /project/home/p200177/DE_371/angeliquebonamy/anemoi/TEST/

  files:
    dataset: arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6.zarr
    graph: /project/home/p200177/DE_371/avritj/multi_scale_res9.pt
    # graph: /project/home/p200177/DE_371/avritj/graph_AROME_full.pt
    # graph: /project/home/p200177/DE_371/angeliquebonamy/anemoi/graph/graph_AROME_full.pt

  num_gpus_per_node: 4
  num_gpus_per_model: 2
  # num_nodes: 4

training:
  max_steps: 15000
  # max_epochs: 500
  model_task: anemoi.training.train.tasks.GraphUnconditionalDiffusionForecaster
  training_approach: probabilistic_high_noise

