overwrite: True
data: data
hidden: hidden

nodes:
  # Data nodes
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset:
        - dataset: path/to/dataset # <-- replace here
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.PlanarAreaWeights
        norm: unit-max # options: l1, l2, unit-max, unit-sum, unit-std

  # Hidden nodes
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.LimitedAreaTriNodes
      resolution: 9 
      reference_node_name: data
edges:
# Encoder configuration
- source_name: data
  target_name: hidden
  edge_builders:
    - _target_: anemoi.graphs.edges.CutOffEdges 
      cutoff_factor: 1 
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength #
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection 
      norm: unit-std
  # Processor configuration
- source_name: hidden
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.MultiScaleEdges 
    x_hops: 1 
    scale_resolutions: 9
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
  # Decoder configuration
- source_name: hidden
  target_name: data
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges 
    num_nearest_neighbours: 3 
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

post_processors:
  - _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
    nodes_name: data
    save_mask_indices_to_attr: indices_connected_nodes # optional
